# Generated by Django 4.1.7 on 2023-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(choices=[('Participation', 'Participation'), ('Winner', 'Winner')], default='participation', max_length=20)),
            ],
        ),
    ]
